# Generated by Django 5.2 on 2025-04-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_task_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="retry_delay",
            new_name="initial_interval",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="retry_attempts",
            new_name="maximum_attempts",
        ),
        migrations.AddField(
            model_name="task",
            name="back_off",
            field=models.FloatField(default=2.0),
        ),
    ]
