# Generated by Django 5.2 on 2025-04-23 04:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0003_rename_retry_delay_task_initial_interval_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workflow",
            old_name="delay_seconds",
            new_name="delay_minutes",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="month",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="temporal_schedule_id",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="schedule",
            name="day_of_month",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="day_of_week",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="hour",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(23),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="minute",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(59),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="workflow",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule",
                to="workflows.workflow",
            ),
        ),
    ]
