# Generated by Django 5.2 on 2025-04-22 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskexecution",
            name="next_retry_at",
        ),
        migrations.RemoveField(
            model_name="taskexecution",
            name="retry_count",
        ),
    ]
