# Generated by Django 5.2 on 2025-04-23 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0003_remove_taskexecution_temporal_activity_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="execution",
            name="temporal_run_id",
        ),
    ]
